# Cluster command
cluster: mkdir -p logs/{rule} &&
  sbatch
  --partition={resources.partition}
  --cpus-per-task={resources.threads}
  --mem={resources.mem_mb}
  --job-name=bpp-{rule}-{wildcards}
  --output=logs/{rule}/%j.out
  --error=logs/{rule}/%j.out
  --time={resources.time}


# Default ressources for all rules
default-resources:
  - partition=medium
  - mem_mb=64000
  - threads=11
  - time="12:00:00"


max-jobs-per-second: 100
max-status-checks-per-second: 100
local-cores: 1
latency-wait: 200
jobs: 100

# 4 attempts to restart to correspond to the progressive memory increase solving OOM
restart-times: 2
keep-going: True
rerun-incomplete: True
# scheduler: greedy

use-conda: true
conda-frontend: "mamba"
